### ISSUE TITLE
conda-forge

### ISSUE THREAD

**Issue by JoelStansbury** [JoelStansbury/jp_noui#2]
need a working meta.yaml.

Here is the current attempt... The build complains about `hatch` being unable to find `nodejs`. Not sure if hatch is even required (it is not needed for `pip install` on my machine). `hatch` appears in the `pyproject.toml` included in the official labextension cookiecutter [extension-cookiecutter-ts](https://github.com/jupyterlab/extension-cookiecutter-ts). At any rate, it seems to be causing issues with conda build and there is little info about how to package extensions for conda so there's a lot of trial and error involved here.

```yml
{% set version = "0.1.0" %}

package:
  name: jp-noui
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jp_noui/jp_noui-{{ version }}.tar.gz
  sha256: 4e1e8ba5c9aef02432559d234c751bddccfbf72ede3902ef7cd2dc9fcac50a1c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.7
    - nodejs
    - hatch-jupyter-builder
    - jupyter-releaser
  
  run:
    - python >=3.7
  
  run_constrained:
    - jupyterlab >=3,<4

test:
  requires:
    - pip
  imports:
    - jp_noui
  commands:
    - pip check
    - jupyter labextension list

about:
  home: https://github.com/JoelStansbury/jp-noui
  summary: Hides jupyterlab UI elements for presentable notebook applications
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - JoelStansbury
```

current error:
```
hatchling.plugin.exceptions.UnknownPluginError: Unknown metadata hook: nodejs
```

potentially related to:
https://github.com/pypa/hatch/issues/599
